import org.junit.Test;
import static org.junit.Assert.*;
import com.zoonies.cinc.connectors.pollen.*;
/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'tboyles' at '12/6/14 1:57 AM' with Gradle 2.0
 *
 * @author tboyles, @date 12/6/14 1:57 AM
 */
public class PollenTest {
    @Test public void testSomeLibraryMethod() {
        Pollen classUnderTest = new Pollen();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
