package com.zoonies.cinc.connectors.pollen;

import org.jsoup.Jsoup;
import org.jsoup.helper.Validate;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.select.Elements;
import java.sql.*;


/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'tboyles' at '12/6/14 1:57 AM' with Gradle 2.0
 *
 * @author pocketilmatto, @date 12/6/14 1:57 AM
 */
public class Pollen {

    private static String url = "http://www.wunderground.com/DisplayPollen.asp?Zipcode=94402";
    private static String location_param;
    // JDBC driver name and database URL
    static final String JDBC_DRIVER = "com.mysql.jdbc.Driver";  
    static String db_url;

    //  Database credentials
    static String db_user;
    static String db_pass;
   

    public static void main(String[] args) {
        String url_params = "";
        db_url = args[0];
        db_user = args[1];
        db_pass = args[2];
        if (args.length > 3)
        {
            location_param = args[3];
            url_params = "?Zipcode="+args[3];
            url = url + url_params;
        }

        try {
            getRawPollenData();
            //System.out.println(getRawPollenData());
        } catch (Exception e) {
            System.out.println("Something went wrong!");
        }
    }

    public static void insertData(Float pollen_count) {
      Connection conn = null;
      Statement stmt = null;
      try{
         Class.forName(JDBC_DRIVER);
         conn = DriverManager.getConnection(db_url, db_user, db_pass);
         stmt = conn.createStatement();
         
         String sql = " insert into stream_pollen (measure, zip)"
           + " values ("+pollen_count+", "+location_param+")";
         stmt.executeUpdate(sql);
         
         System.out.println("Inserted records into the table...");

      }catch(SQLException se){
         //Handle errors for JDBC
         se.printStackTrace();
      }catch(Exception e){
         //Handle errors for Class.forName
         e.printStackTrace();
      }finally{
         //finally block used to close resources
        try{
         if(stmt!=null)
            conn.close();
        }catch(SQLException se){
        }// do nothing
        try{
         if(conn!=null)
            conn.close();
        }catch(SQLException se){
            se.printStackTrace();
        }//end finally try
      }//end try
      
   }//end main

    public static String getRawPollenData() throws Exception {
        String rawPollenData = "";
        try {
            Document doc = Jsoup.connect(url).get();
            Element level = doc.getElementsByClass("levels").first();
            String pollen = level.html();
            pollen = pollen.split("<p>")[1].split("</p>")[0];
            insertData(Float.parseFloat(pollen));

        } catch (Exception e) {
            throw new Exception ("Something untoward has happened: " + e.toString());
        }

        return rawPollenData;
    }

    public boolean someLibraryMethod() {
        return true;
    }
}
